{{- if .Values.rbac.enable }}
# This rule is not used by the project fallernetes itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gameserver.falloria.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/name: fallernetes
    app.kubernetes.io/managed-by: kustomize
  name: fleet-editor-role
rules:
- apiGroups:
  - gameserver.falloria.com
  resources:
  - fleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameserver.falloria.com
  resources:
  - fleets/status
  verbs:
  - get
{{- end -}}
