name: Operator E2E Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.filter.outputs.run-tests }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            run-tests:
              - 'operator/internal/**'
              - 'operator/api/**'
              - '.github/workflows/operator-e2e-test.yml'
              - 'operator/test/**'

  test-e2e:
    name: Run E2E Tests
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check if test should run
        if: needs.changes.outputs.run-tests != 'true'
        run: echo "No relevant changes. Skipping tests."

      - name: Setup Go
        if: needs.changes.outputs.run-tests == 'true'
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./operator/go.mod

      - name: Cache operator tools
        if: needs.changes.outputs.run-tests == 'true'
        uses: actions/cache@v4
        with:
          path: operator/bin
          key: operator-tools-${{ runner.os }}-${{ hashFiles('operator/Makefile') }}

      - name: Install the latest version of kind
        if: needs.changes.outputs.run-tests == 'true'
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        if: needs.changes.outputs.run-tests == 'true'
        run: kind version

      - name: Running Tests
        if: needs.changes.outputs.run-tests == 'true'
        working-directory: operator
        run: |
          go mod tidy
          make test-e2e
        env:
          GITHUB_ACTIONS: true
