name: Tests

on:
  pull_request:
    paths-ignore:
      - "dist/**"

jobs:
  test-e2e-helm:
    name: Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - run: echo "No relevant changes detected."
