name: Tests

on:
  pull_request:
    paths-ignore:
      - "internal/**"
      - "api/**"

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - run: echo "No relevant changes detected."
